### PR TITLE
instrumentation: include functions with specific calls

### PR DESCRIPTION
**Pull request by Maetveis**
Add the option `--caller-include <regex>` or environment variable `OMNITRACE_REGEX_CALLER_INCLUDE` to instrument functions which contain call to a set of functions, E.g. `--caller-include foo` instruments any function which calls `foo`.

Closes: #199

### CODE REVIEW

**Review by jrmadsen — CHANGES_REQUESTED** [review]
Please add the value of this check to the `module_function::serialize(ArchiveT& ar, const unsigned)`

**Comment by jrmadsen** [comment]
We also need a test for this. I can do this or if you want to, here's what's needed: 

Create a rewrite-caller-include toy app in examples and then drop a test into tests/CMakeLists.txt. You can add the options to the macro `SKIP_PRELOAD SKIP_RUNTIME` (to just restrict it to the binary rewrite), set the REWRITE_ARGS to whatever is necessary to include the interior function but exclude the exterior (probably set the `-i` flag to something large and then `-I` flag to the interior function), and then pass in these (minimal) environment options:

```console
OMNITRACE_USE_TIMEMORY=ON
OMNITRACE_COUT_OUTPUT=ON
```

and then write a REWRITE_RUN_PASS_REGEX to make sure that the caller is in the output.

**Comment by jrmadsen** [comment]
If you have clang-format-11 on your system, run `make format` to apply the source code formatting

**Comment by Maetveis** [comment]
> Please add the value of this check to the `module_function::serialize(ArchiveT& ar, const unsigned)`

It is already part of `is_user_included`, should I add a separate top level function instead and add that?

**Comment by jrmadsen** [comment]
Although actually that's not really necessary. It fits under the `is_user_included` but provides extra info that it was user included because of the caller-include field

**Comment by jrmadsen** [comment]
Also, no need to squash for force a push, I squash before I merge and I think you squashing causes me to have to reapproved running the workflows for first time contributors.

**Comment by jrmadsen** [comment]
@Maetveis I tweaked the tests in https://github.com/StreamHPC/omnitrace/pull/1. Also, it looks like some of the rewrites are failing the regex test. It looks like they aren't instrumenting anything.... If this continues, try setting the build type of the example to Debug to avoid any optimizations.

**Comment by Maetveis** [comment]
> Also, it looks like some of the rewrites are failing the regex test. It looks like they aren't instrumenting anything.... If this continues, try setting the build type of the example to Debug to avoid any optimizations.

Looking at compiler explorer I couldn't get any combination to omit the calls even with flto, and from the failed jobs artifacts its visible that the functions are there, just not getting instrumented (they are listed in available.txt). Would be good to have the compiled executable from the CI job to check out the assembly, maybe dyninst is not picking up on tail-calls properly?

Anyway I gave up for now and set the example to debug, hopefully that will fix it.

**Comment by jrmadsen** [comment]
> Looking at compiler explorer I couldn't get any gcc version to omit the calls even with `-flto` when the `noinline` attribute is present, and from the failed jobs' artifacts its visible that the functions are there, just not getting instrumented (they are listed in available.txt). Would be good to have the compiled executable from the CI job to check out the assembly, maybe dyninst is not picking up on tail-calls properly?

I haven't looked at the assembly or any details but I would guess it is the "don't instrument with traps" heuristic that is triggering the omission since that check will return false before it ever gets to the "is_user_included" check.

**Comment by Maetveis** [comment]
> I haven't looked at the assembly or any details but I would guess it is the "don't instrument with traps" heuristic that is triggering the omission since that check will return false before it ever gets to the "is_user_included" check:

Without access to the assembly I don't know how to debug this further, if you want to take dive, feel free, but I'm happy with the test as is.

**Review by jrmadsen — APPROVED** [review]

**Pull request merged**
